export const forms = {
    REQUIRED: 'FORMS.REQUIRED',
    INVALID_PASSWORD: 'FORMS.INVALID_PASSWORD',
    INVALID_EMAIL: 'FORMS.INVALID_EMAIL',
    EMAIL_NOT_MATCH: 'FORMS.EMAIL_NOT_MATCH',
    PASSWORD_NOT_MATCH: 'FORMS.PASSWORD_NOT_MATCH'
}

